spring.application.name=marvellousportal

spring.data.mongodb.uri=mongodb://localhost:27017/marvellousportal
spring.data.mongodb.database=marvellousdb
jwt.secret=marvellous-super-secret-key-change-this-in-production
jwt.expiration=86400000